from __future__ import annotations

"""Language model v3 prompt types.

A prompt is a list of messages.

Note: Not all models and prompt formats support multi-modal inputs and
tool calls. The validation happens at runtime.

Note: This is not a user-facing prompt. The AI SDK methods will map the
user-facing prompt types such as chat or instruction prompts to this format.

Translated from: packages/provider/src/language-model/v3/language-model-v3-prompt.ts
"""

from dataclasses import dataclass, field
from typing import Literal, Union

from ai_sdk.provider.json_value.json_value import JSONValue
from ai_sdk.provider.language_model.v3.language_model_v3_data_content import (
    LanguageModelV3DataContent,
)
from ai_sdk.provider.shared.v3.shared_v3_provider_options import (
    SharedV3ProviderOptions,
)


# --- Prompt content parts ---


@dataclass(frozen=True)
class LanguageModelV3TextPart:
    """Text content part of a prompt. It contains a string of text."""

    type: Literal['text'] = 'text'

    text: str = ''
    """The text content."""

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3ReasoningPart:
    """Reasoning content part of a prompt. It contains a string of reasoning text."""

    type: Literal['reasoning'] = 'reasoning'

    text: str = ''
    """The reasoning text."""

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3FilePart:
    """File content part of a prompt. It contains a file."""

    type: Literal['file'] = 'file'

    data: LanguageModelV3DataContent = ''
    """File data. Can be bytes, base64 encoded data as a string or a URL."""

    media_type: str = ''
    """IANA media type of the file.

    Can support wildcards, e.g. ``image/*`` (in which case the provider
    needs to take appropriate action).

    See https://www.iana.org/assignments/media-types/media-types.xhtml
    """

    filename: str | None = None
    """Optional filename of the file."""

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3ToolCallPart:
    """Tool call content part of a prompt. It contains a tool call (usually generated by the AI model)."""

    type: Literal['tool-call'] = 'tool-call'

    tool_call_id: str = ''
    """ID of the tool call. This ID is used to match the tool call with the tool result."""

    tool_name: str = ''
    """Name of the tool that is being called."""

    input: object = None  # type: ignore[assignment]
    """Arguments of the tool call. This is a JSON-serializable object that matches the tool's input schema."""

    provider_executed: bool | None = None
    """Whether the tool call will be executed by the provider.
    If this flag is not set or is false, the tool call will be executed by the client."""

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultPart:
    """Tool result content part of a prompt. It contains the result of the tool call with the matching ID."""

    type: Literal['tool-result'] = 'tool-result'

    tool_call_id: str = ''
    """ID of the tool call that this result is associated with."""

    tool_name: str = ''
    """Name of the tool that generated this result."""

    output: LanguageModelV3ToolResultOutput | None = None
    """Result of the tool call."""

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3ToolApprovalResponsePart:
    """Tool approval response content part of a prompt.

    It contains the user's decision to approve or deny a provider-executed tool call.
    """

    type: Literal['tool-approval-response'] = 'tool-approval-response'

    approval_id: str = ''
    """ID of the approval request that this response refers to."""

    approved: bool = False
    """Whether the approval was granted (True) or denied (False)."""

    reason: str | None = None
    """Optional reason for approval or denial."""

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


# --- Tool result output types ---


@dataclass(frozen=True)
class LanguageModelV3ToolResultTextOutput:
    """Text tool output that should be directly sent to the API."""

    type: Literal['text'] = 'text'

    value: str = ''

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultJsonOutput:
    """JSON tool output."""

    type: Literal['json'] = 'json'

    value: JSONValue = None

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultExecutionDeniedOutput:
    """Type when the user has denied the execution of the tool call."""

    type: Literal['execution-denied'] = 'execution-denied'

    reason: str | None = None
    """Optional reason for the execution denial."""

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultErrorTextOutput:
    """Error text tool output."""

    type: Literal['error-text'] = 'error-text'

    value: str = ''

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultErrorJsonOutput:
    """Error JSON tool output."""

    type: Literal['error-json'] = 'error-json'

    value: JSONValue = None

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


# --- Content value parts (used in 'content' type tool result output) ---


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentText:
    """Text content."""

    type: Literal['text'] = 'text'

    text: str = ''
    """Text content."""

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentFileData:
    """File data content."""

    type: Literal['file-data'] = 'file-data'

    data: str = ''
    """Base-64 encoded media data."""

    media_type: str = ''
    """IANA media type.

    See https://www.iana.org/assignments/media-types/media-types.xhtml
    """

    filename: str | None = None
    """Optional filename of the file."""

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentFileUrl:
    """File URL content."""

    type: Literal['file-url'] = 'file-url'

    url: str = ''
    """URL of the file."""

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentFileId:
    """File ID content."""

    type: Literal['file-id'] = 'file-id'

    file_id: str | dict[str, str] = ''
    """ID of the file.

    If you use multiple providers, you need to specify the provider specific
    ids using the dict option. The key is the provider name, e.g. 'openai'
    or 'anthropic'.
    """

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentImageData:
    """Images that are referenced using base64 encoded data."""

    type: Literal['image-data'] = 'image-data'

    data: str = ''
    """Base-64 encoded image data."""

    media_type: str = ''
    """IANA media type.

    See https://www.iana.org/assignments/media-types/media-types.xhtml
    """

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentImageUrl:
    """Images that are referenced using a URL."""

    type: Literal['image-url'] = 'image-url'

    url: str = ''
    """URL of the image."""

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentImageFileId:
    """Images that are referenced using a provider file id."""

    type: Literal['image-file-id'] = 'image-file-id'

    file_id: str | dict[str, str] = ''
    """Image that is referenced using a provider file id.

    If you use multiple providers, you need to specify the provider specific
    ids using the dict option. The key is the provider name, e.g. 'openai'
    or 'anthropic'.
    """

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentCustom:
    """Custom content part.

    This can be used to implement provider-specific content parts.
    """

    type: Literal['custom'] = 'custom'

    provider_options: SharedV3ProviderOptions | None = None
    """Provider-specific options."""


LanguageModelV3ToolResultContentPart = Union[
    LanguageModelV3ToolResultContentText,
    LanguageModelV3ToolResultContentFileData,
    LanguageModelV3ToolResultContentFileUrl,
    LanguageModelV3ToolResultContentFileId,
    LanguageModelV3ToolResultContentImageData,
    LanguageModelV3ToolResultContentImageUrl,
    LanguageModelV3ToolResultContentImageFileId,
    LanguageModelV3ToolResultContentCustom,
]


@dataclass(frozen=True)
class LanguageModelV3ToolResultContentOutput:
    """Content tool output containing multiple content parts."""

    type: Literal['content'] = 'content'

    value: list[LanguageModelV3ToolResultContentPart] = field(default_factory=list)


LanguageModelV3ToolResultOutput = Union[
    LanguageModelV3ToolResultTextOutput,
    LanguageModelV3ToolResultJsonOutput,
    LanguageModelV3ToolResultExecutionDeniedOutput,
    LanguageModelV3ToolResultErrorTextOutput,
    LanguageModelV3ToolResultErrorJsonOutput,
    LanguageModelV3ToolResultContentOutput,
]
"""Result of a tool call."""


# --- Message types ---

# Note: there could be additional parts for each role in the future,
# e.g. when the assistant can return images or the user can share files
# such as PDFs.


@dataclass(frozen=True)
class LanguageModelV3SystemMessage:
    """System message."""

    role: Literal['system'] = 'system'

    content: str = ''

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3UserMessage:
    """User message."""

    role: Literal['user'] = 'user'

    content: list[LanguageModelV3TextPart | LanguageModelV3FilePart] = field(
        default_factory=list
    )

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3AssistantMessage:
    """Assistant message."""

    role: Literal['assistant'] = 'assistant'

    content: list[
        Union[
            LanguageModelV3TextPart,
            LanguageModelV3FilePart,
            LanguageModelV3ReasoningPart,
            LanguageModelV3ToolCallPart,
            LanguageModelV3ToolResultPart,
        ]
    ] = field(default_factory=list)

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV3ToolMessage:
    """Tool message."""

    role: Literal['tool'] = 'tool'

    content: list[
        Union[
            LanguageModelV3ToolResultPart,
            LanguageModelV3ToolApprovalResponsePart,
        ]
    ] = field(default_factory=list)

    provider_options: SharedV3ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


LanguageModelV3Message = Union[
    LanguageModelV3SystemMessage,
    LanguageModelV3UserMessage,
    LanguageModelV3AssistantMessage,
    LanguageModelV3ToolMessage,
]

LanguageModelV3Prompt = list[LanguageModelV3Message]
"""A prompt is a list of messages.

Note: Not all models and prompt formats support multi-modal inputs and
tool calls. The validation happens at runtime.

Note: This is not a user-facing prompt. The AI SDK methods will map the
user-facing prompt types such as chat or instruction prompts to this format.
"""
