from __future__ import annotations

"""A file that has been generated by the model.

Generated files as base64 encoded strings or binary data.
The files should be returned without any unnecessary conversion.

Translated from: packages/provider/src/language-model/v3/language-model-v3-file.ts
"""

from dataclasses import dataclass, field
from typing import Literal

from ai_sdk.provider.shared.v3.shared_v3_provider_metadata import (
    SharedV3ProviderMetadata,
)


@dataclass(frozen=True)
class LanguageModelV3File:
    """A file that has been generated by the model.

    Generated files as base64 encoded strings or binary data.
    The files should be returned without any unnecessary conversion.
    """

    type: Literal['file'] = 'file'

    media_type: str = ''
    """The IANA media type of the file, e.g. ``image/png`` or ``audio/mp3``.

    See https://www.iana.org/assignments/media-types/media-types.xhtml
    """

    data: str | bytes = b''
    """Generated file data as base64 encoded strings or binary data.

    The file data should be returned without any unnecessary conversion.
    If the API returns base64 encoded strings, the file data should be returned
    as base64 encoded strings. If the API returns binary data, the file data should
    be returned as binary data.
    """

    provider_metadata: SharedV3ProviderMetadata | None = None
    """Optional provider-specific metadata for the file part."""
