from __future__ import annotations

"""Language model v2 prompt types.

A prompt is a list of messages.

Note: Not all models and prompt formats support multi-modal inputs and
tool calls. The validation happens at runtime.

Note: This is not a user-facing prompt. The AI SDK methods will map the
user-facing prompt types such as chat or instruction prompts to this format.

Translated from: packages/provider/src/language-model/v2/language-model-v2-prompt.ts
"""

from dataclasses import dataclass, field
from typing import Any, Literal, Union

from ...json_value.json_value import JSONValue
from .language_model_v2_data_content import (
    LanguageModelV2DataContent,
)
from ...shared.v2.shared_v2_provider_options import (
    SharedV2ProviderOptions,
)


# Note: there could be additional parts for each role in the future,
# e.g. when the assistant can return images or the user can share files
# such as PDFs.


@dataclass(frozen=True)
class LanguageModelV2TextPart:
    """Text content part of a prompt. It contains a string of text."""

    type: Literal['text'] = 'text'

    text: str = ''
    """The text content."""

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV2ReasoningPart:
    """Reasoning content part of a prompt. It contains a string of reasoning text."""

    type: Literal['reasoning'] = 'reasoning'

    text: str = ''
    """The reasoning text."""

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV2FilePart:
    """File content part of a prompt. It contains a file."""

    type: Literal['file'] = 'file'

    data: LanguageModelV2DataContent = ''
    """File data. Can be bytes, base64 encoded data as a string or a URL."""

    media_type: str = ''
    """IANA media type of the file.

    Can support wildcards, e.g. ``image/*`` (in which case the provider
    needs to take appropriate action).

    See https://www.iana.org/assignments/media-types/media-types.xhtml
    """

    filename: str | None = None
    """Optional filename of the file."""

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV2ToolCallPart:
    """Tool call content part of a prompt. It contains a tool call (usually generated by the AI model)."""

    type: Literal['tool-call'] = 'tool-call'

    tool_call_id: str = ''
    """ID of the tool call. This ID is used to match the tool call with the tool result."""

    tool_name: str = ''
    """Name of the tool that is being called."""

    input: Any = None
    """Arguments of the tool call. This is a JSON-serializable object that matches the tool's input schema."""

    provider_executed: bool | None = None
    """Whether the tool call will be executed by the provider.
    If this flag is not set or is False, the tool call will be executed by the client."""

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


# --- Tool result output types ---


@dataclass(frozen=True)
class LanguageModelV2ToolResultTextOutput:
    """Text output from a tool result."""

    type: Literal['text'] = 'text'
    value: str = ''


@dataclass(frozen=True)
class LanguageModelV2ToolResultJsonOutput:
    """JSON output from a tool result."""

    type: Literal['json'] = 'json'
    value: JSONValue = None


@dataclass(frozen=True)
class LanguageModelV2ToolResultErrorTextOutput:
    """Error text output from a tool result."""

    type: Literal['error-text'] = 'error-text'
    value: str = ''


@dataclass(frozen=True)
class LanguageModelV2ToolResultErrorJsonOutput:
    """Error JSON output from a tool result."""

    type: Literal['error-json'] = 'error-json'
    value: JSONValue = None


@dataclass(frozen=True)
class LanguageModelV2ToolResultContentText:
    """Text content within a tool result content output."""

    type: Literal['text'] = 'text'

    text: str = ''
    """Text content."""


@dataclass(frozen=True)
class LanguageModelV2ToolResultContentMedia:
    """Media content within a tool result content output."""

    type: Literal['media'] = 'media'

    data: str = ''
    """Base-64 encoded media data."""

    media_type: str = ''
    """IANA media type.

    See https://www.iana.org/assignments/media-types/media-types.xhtml
    """


@dataclass(frozen=True)
class LanguageModelV2ToolResultContentOutput:
    """Content output from a tool result."""

    type: Literal['content'] = 'content'
    value: list[LanguageModelV2ToolResultContentText | LanguageModelV2ToolResultContentMedia] = field(
        default_factory=list
    )


LanguageModelV2ToolResultOutput = Union[
    LanguageModelV2ToolResultTextOutput,
    LanguageModelV2ToolResultJsonOutput,
    LanguageModelV2ToolResultErrorTextOutput,
    LanguageModelV2ToolResultErrorJsonOutput,
    LanguageModelV2ToolResultContentOutput,
]


@dataclass(frozen=True)
class LanguageModelV2ToolResultPart:
    """Tool result content part of a prompt. It contains the result of the tool call with the matching ID."""

    type: Literal['tool-result'] = 'tool-result'

    tool_call_id: str = ''
    """ID of the tool call that this result is associated with."""

    tool_name: str = ''
    """Name of the tool that generated this result."""

    output: LanguageModelV2ToolResultOutput | None = None
    """Result of the tool call."""

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


# --- Message types ---


@dataclass(frozen=True)
class LanguageModelV2SystemMessage:
    """System message in a prompt."""

    role: Literal['system'] = 'system'
    content: str = ''

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV2UserMessage:
    """User message in a prompt."""

    role: Literal['user'] = 'user'
    content: list[LanguageModelV2TextPart | LanguageModelV2FilePart] = field(
        default_factory=list
    )

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV2AssistantMessage:
    """Assistant message in a prompt."""

    role: Literal['assistant'] = 'assistant'
    content: list[
        LanguageModelV2TextPart
        | LanguageModelV2FilePart
        | LanguageModelV2ReasoningPart
        | LanguageModelV2ToolCallPart
        | LanguageModelV2ToolResultPart
    ] = field(default_factory=list)

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


@dataclass(frozen=True)
class LanguageModelV2ToolMessage:
    """Tool message in a prompt."""

    role: Literal['tool'] = 'tool'
    content: list[LanguageModelV2ToolResultPart] = field(default_factory=list)

    provider_options: SharedV2ProviderOptions | None = None
    """Additional provider-specific options. They are passed through
    to the provider from the AI SDK and enable provider-specific
    functionality that can be fully encapsulated in the provider."""


LanguageModelV2Message = Union[
    LanguageModelV2SystemMessage,
    LanguageModelV2UserMessage,
    LanguageModelV2AssistantMessage,
    LanguageModelV2ToolMessage,
]

LanguageModelV2Prompt = list[LanguageModelV2Message]
"""A prompt is a list of messages.

Note: Not all models and prompt formats support multi-modal inputs and
tool calls. The validation happens at runtime.

Note: This is not a user-facing prompt. The AI SDK methods will map the
user-facing prompt types such as chat or instruction prompts to this format.
"""
